### ISSUE TITLE
commit message 잘려서 혹시나 해서 올려봅니다

### ISSUE THREAD

**Issue by tqx7514** [SonGangMin/CarCarO#2]
faq에 자주묻는 질문 파트 class추가 후 css로 위치 조정
자주묻는질문 데이터베이스 연결해서 들어가게 한 후 스크롤로 내려볼 수 있게 설정
faq제목 누르면 컨텐츠로 이동하게 하기위한 작업 시작
했습니다~

**Comment by SonGangMin** [comment]
확인~

**Comment by SonGangMin** [comment]
네
